feat: get mentor by availability
YouthCatalyst/calendar pull request #7
Opened 2024-08-14 09:12 UTC by Andrew4Coding

- Get mentor by availability

2024-08-15 21:53 UTC, daniyusra commented on apps/api/v1/pages/api/availabilities/mentors/_get.ts
> +    body,
Why not use query parameters? Using body in a get request is unorthodox to say the least. 

Other API examples from the same subfolder to use query parameters are as follows

apps/api/v1/pages/api/availability/_get.ts
apps/api/v1/pages/api/bookings/_get.ts

2024-08-17 02:20 UTC, daniyusra commented
The routing of the path seems to be confusing, not easy to access, and inconsistent with the design document. It might not be accessible at all. 

Rather than putting in the current path, which is 

`apps/api/v1/pages/api/availabilities/mentors/_get.ts`

I suggest putting it into the following directory

`apps/web/pages/api/availability`

With the following path

`apps/web/pages/api/availability/mentor-by-availabiltiy.ts`

Don't forget to make changes in the design document!

2024-08-17 02:21 UTC, daniyusra requested changes
The routing of the path seems to be confusing, not easy to access, and inconsistent with the design document. It might not be accessible at all.

Rather than putting in the current path, which is

apps/api/v1/pages/api/availabilities/mentors/_get.ts

I suggest putting it into the following directory

apps/web/pages/api/availability

With the following path

apps/web/pages/api/availability/mentor-by-availabiltiy.ts

Don't forget to make changes in the design document!

2024-08-22 12:56 UTC, Andrew4Coding commented on apps/web/pages/api/availabilities/mentor-by-availability.ts
> +    console.log(selectedUsers);
Overall udah bagus sih kak, maybe ini di remove aja console.log nya

2024-08-22 15:21 UTC, merged